In [0]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Read the input file and check the data dimension

In [2]:
from google.colab import drive
drive.mount('/content/drive') 

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
gc_df = pd.read_csv("/content/drive/My Drive/GreatlakesAIML/german_credit.csv")
gc_df.head()

default  ... foreign_worker
0        0  ...            yes
1        1  ...            yes
2        0  ...            yes
3        0  ...            yes
4        1  ...            yes

[5 rows x 21 columns]

In [4]:
# Dimension of data
print("Dimension of data:", gc_df.shape)

# Dimension of dataframe
print("Dimension of dataframe:", gc_df.ndim)

Dimension of data: (1000, 21)
Dimension of dataframe: 2


In [5]:
# Trying to evaluate the data

# Information about dataframe
gc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
default                       1000 non-null int64
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000

In [6]:
# Columns of dataframe
print("Columns of dataframe:", gc_df.columns)

Columns of dataframe: Index(['default', 'account_check_status', 'duration_in_month',
       'credit_history', 'purpose', 'credit_amount', 'savings',
       'present_emp_since', 'installment_as_income_perc',
       'personal_status_sex', 'other_debtors', 'present_res_since', 'property',
       'age', 'other_installment_plans', 'housing', 'credits_this_bank', 'job',
       'people_under_maintenance', 'telephone', 'foreign_worker'],
      dtype='object')


### Q1 Randomly select 50% data for this use case( 1 Marks)
###### Hint: Use train_test_split

In [0]:
# Lets build an Ensemble model but need to modify the dataset first

In [0]:
from sklearn.model_selection import train_test_split
gc_df_half1, gc_df_half2 = train_test_split(gc_df, test_size=0.5, random_state = 101)

In [9]:
gc_df_half1.shape

(500, 21)

### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [0]:
# Convert categorical variable into dummy/indicator variables. As many columns will be created as distinct values
german_credit = pd.get_dummies(gc_df_half1, columns=['account_check_status', 'credit_history', 'purpose', 'savings', 'present_emp_since', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker'])

In [0]:
#To convert it into a model, we drop the column 'default'
german_credit_model = german_credit.drop(['default'], axis = 1)

In [12]:
# Printing Shape of model data
german_credit_model.shape

(500, 61)

### Check for highly correlated variables but don't required any treatment for this use case

In [13]:
german_credit.corr().transpose()

default  ...  foreign_worker_yes
default                                             1.000000  ...            0.076630
duration_in_month                                   0.223669  ...            0.131336
credit_amount                                       0.100665  ...            0.081613
installment_as_income_perc                          0.107718  ...            0.041957
present_res_since                                   0.001447  ...            0.046304
age                                                -0.104182  ...            0.017796
credits_this_bank                                  -0.046802  ...           -0.023587
people_under_maintenance                           -0.027276  ...           -0.084458
account_check_status_0 <= ... < 200 DM              0.139990  ...            0.077347
account_check_status_< 0 DM                         0.239409  ...           -0.095678
account_check_status_>= 200 DM / salary assignm... -0.034582  ...           -0.033507
account_check_status_no checking account           -0.326757  ...            0.031812
credit_history_all credits at this bank paid ba...  0.167648  ...            0.038408
credit_history_critical account/ other credits ... -0.195993  ...           -0.065479
credit_history_delay in paying off in the past     -0.030663  ...            0.057808
credit_history_existing credits paid back duly ...  0.102907  ...            0.003859
credit_history_no credits taken/ all credits pa...  0.100229  ...            0.034953
purpose_(vacation - does not exist?)                0.076844  ...            0.043642
purpose_business                                   -0.010644  ...            0.068437
purpose_car (new)                                   0.099416  ...           -0.196426
purpose_car (used)                                 -0.135378  ...            0.066983
purpose_domestic appliances                        -0.082844  ...            0.093960
purpose_education                                  -0.035944  ...           -0.065350
purpose_furniture/equipment                         0.094611  ...            0.017848
purpose_radio/television                            0.027927  ...           -0.013606
purpose_repairs                                     0.063187  ...            0.025344
purpose_retraining                                 -0.017498  ...            0.019975
savings_.. >= 1000 DM                              -0.067824  ...           -0.059367
savings_... < 100 DM                                0.171446  ...            0.032411
savings_100 <= ... < 500 DM                        -0.018405  ...           -0.030423
...                                                      ...  ...                 ...
present_emp_since_.. >= 7 years                    -0.051699  ...            0.018986
present_emp_since_... < 1 year                      0.131211  ...           -0.020290
present_emp_since_1 <= ... < 4 years                0.007650  ...            0.000943
present_emp_since_4 <= ... < 7 years               -0.090108  ...           -0.039411
present_emp_since_unemployed                        0.017132  ...            0.055360
personal_status_sex_female : divorced/separated...  0.055579  ...            0.045867
personal_status_sex_male : divorced/separated       0.034224  ...            0.043642
personal_status_sex_male : married/widowed          0.021308  ...           -0.015235
personal_status_sex_male : single                  -0.078351  ...           -0.052840
other_debtors_co-applicant                          0.048616  ...           -0.102174
other_debtors_guarantor                            -0.034638  ...           -0.133575
other_debtors_none                                 -0.007955  ...            0.172159
property_if not A121 : building society savings... -0.026635  ...           -0.087810
property_if not A121/A122 : car or other, not i...  0.062224  ...            0.118568
property_real estate                               -0.096358  ...           -0.105695
property_un

### Drop the original variables which are converted to dummy

In [14]:
# Convert categorical variable into dummy/indicator variables. As many columns will be created as distinct values
gc_df = gc_df.drop(['account_check_status', 'credit_history', 'purpose', 'savings', 'present_emp_since', 'personal_status_sex', 'other_debtors', 'property', 'other_installment_plans', 'housing', 'job', 'telephone', 'foreign_worker'], axis = 1)
gc_df.shape

(1000, 8)

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [0]:
# Splitting the dataframe into training and test set in the ratio of 70:30 
Y = gc_df['default']
X = gc_df.drop(['default'], axis = 1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 101)

### Q4 Build Random Forest Model( 1 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection
model = RandomForestClassifier(n_estimators = 500, n_jobs = 2, criterion = "entropy", random_state = 9999)
RF_fit = model.fit(X, Y)

In [17]:
# predictions
german_credit_predict = RF_fit.predict(X_test)
german_credit_predict

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0])

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_curve, roc_auc_score
print("Accuracy:", accuracy_score(Y_test, german_credit_predict))
print("Confusion Matrix:\n", confusion_matrix(Y_test, german_credit_predict))

Accuracy: 1.0
Confusion Matrix:
 [[204   0]
 [  0  96]]


### Q6 Show the list of the features importance( 1 Marks)

In [19]:
print("Importance of Features:", RF_fit.feature_importances_)

Importance of Features: [0.19079001 0.34200655 0.06800622 0.07512852 0.2488336  0.04858433
 0.02665076]


### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [0]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, cross_val_predict

In [0]:
# Use below values
num_folds = 10
seed = 77

In [0]:
#Validate the Random Forest model build above using k fold

In [0]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [29]:
array_german_credit = gc_df.values
X2 = array_german_credit[:,1:8]
Y2 = array_german_credit[:,0]
# feature extraction
scores = []
kfold = KFold(n_splits=num_folds, random_state=seed, shuffle=False)
for train_index, test_index in kfold.split(X2):
    X2_train, X2_test, y2_train, y2_test = X2[train_index], X2[test_index], Y2[train_index], Y2[test_index]
    scores.append(get_score(RandomForestClassifier(n_estimators = 500, n_jobs = 2, criterion = "entropy", random_state = 9999), X2_train, X2_test, y2_train, y2_test))
scores

[0.78, 0.67, 0.68, 0.75, 0.74, 0.62, 0.71, 0.77, 0.67, 0.7]

In [0]:
#Calculate Mean score

In [30]:
print(np.mean(scores))

0.7090000000000001


In [0]:
# Calculate score standard deviation using std()

In [31]:
print(np.std(scores))

0.04825971404805461


# Q8 Print the confusion matrix( 1 Marks)

In [0]:
y_predict = cross_val_predict(RandomForestClassifier(n_estimators = 500, n_jobs = 2, criterion = "entropy", random_state = 9999), X2, Y2, cv=10)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("Confusion Matrix:\n", confusion_matrix(Y2, y_predict))

Confusion Matrix:
 [[628  72]
 [218  82]]


# Q9.Classification accuracy: 
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [34]:
print("Accuracy:", accuracy_score(Y2, y_predict))

Accuracy: 0.71


# Q10.Plot Receiver Operating Characteristic (ROC) Curves( 1 Marks)

In [0]:
#Hint: Use roc_curve

ROC curve can help you to choose a threshold that balances sensitivity and specificity in a way that makes sense for your particular context

# Q11. Calculate AUC(the percentage of the ROC plot that is underneath the curve) - optional

### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models